# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: 
- master
pool:
  vmImage: 'windows-2019'

variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
stages:
- stage: Build
  jobs:
  - job: Job
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      fetchDepth: 0
    - task: SonarCloudPrepare@1
      enabled: true
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'devopscapdemo'
        scannerMode: 'MSBuild'
        projectKey: 'DevOpsCapDemo_DevSecOpsDemo'
        projectName: 'DevSecOpsDemo'
    - task: NuGetToolInstaller@1
    - task: DotNetCoreCLI@2
      displayName: 'Build the source code'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Test the source code'
      inputs:
        command: 'test'
        projects: '**/*Test**.csproj'
    - task: SonarCloudAnalyze@1
      displayName: 'Sonar Cloud Analyze'
      enabled: true
    - task: SonarCloudPublish@1
      displayName: 'Sonar Cloud Publish'
      enabled: true
      inputs:
        pollingTimeoutSec: '300'
    - task: DotNetCoreCLI@2
      displayName: 'Publish the source code'
      inputs:
        command: 'publish'
        publishWebProjects: true
        modifyOutputPath: false
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishPipelineArtifact@1
      displayName: 'Copy Artifact for Deployment'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'myWebsiteName'
    - script: dotnet pack /p:PackageVersion=$(Build.BuildNumber)  # define version variable elsewhere in your pipeline
      displayName: 'Package for Nuget Feed Publish'
    - task: NuGetAuthenticate@0      
      displayName: 'Authenticate for Nuget Feed Publish'
    - task: NuGetCommand@2
      displayName: 'Nuget Feed Publish'
      inputs:
        command: 'push'
        packagesToPush: '**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '4528bd78-c535-4916-bd8a-59275f5a5306/2918157a-5f27-4741-b144-b7960b2b99b6'

    
        
- stage: Deploy
  jobs:
  - deployment: publishinternal
    displayName: 'Publish the Application'
    environment: PROD
    pool:
      vmImage: 'windows-2019'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'azConn'
              appType: 'webApp'
              WebAppName: 'demowebappforvelocity'
              packageForLinux: '$(Pipeline.Workspace)/**/*.zip'